---
# OS Family: Debian
- name: Update apt when OS Family is Debian
  ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  when: ansible_facts['os_family'] == "Debian"
- name: Upgrade all apt packages
  ansible.builtin.apt: upgrade=dist force_apt_get=yes
  when: ansible_facts['os_family'] == "Debian"
# OS Family: RedHat
- name: Yum for OS Family RedHat
  ansible.builtin.yum: 
    name: '*'
    state: latest
  when: ansible_facts['os_family'] == "RedHat"
- name: Set SELinux for permissive
  ansible.builtin.lineinfile: 
    path: /etc/selinux/config
    regexp: "^SELINUX="
    line: SELINUX=permissive
  when: ansible_facts['os_family'] == "RedHat"
- name: Copy kernel config
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - {src: 98-changeparams.conf, dest: /etc/sysctl.d/98-changeparams.conf, owner: "root", group: "root", mode: "0644"}
    - {src: limits.conf, dest: /etc/security/limits.conf, owner: "root", group: "root", mode: "0644"}
  when: ansible_facts['os_family'] == "RedHat"
- name: Install epel-release
  ansible.builtin.command: amazon-linux-extras install epel -y
  when: ansible_facts['os_family'] == "RedHat"
